### ISSUE TITLE
Beyond binding generation...

### ISSUE THREAD

**Issue by vpenades** [xoofx/CppAst.CodeGen#21]
Yeah, I know starting a title with the "Beyond" keyword is scary!

This is actually a prospective question; about the possibility, in the far future, to be able to convert C++ code to C# ... not just bindings, but the whole thing.

I don't expect it will be possible to make a full converter that works out of the box, we can only hope to have a converter that requires extensive rewriting at best... and there's two main issues that cannot be translated to c# easily:  c++ templates and pointers semantics.

The c++ templating is almost impossible to handle.... and the pointers... I believe, it also was impossible to handle, until recently.

Recently I've been using `Span<T>` a lot, and the more I use it, the more I recall when I used to program in c++, and I've began thinking about all the code I ported from c++ to c#, how difficult it was to port due to the pointer semantics, and how easily could have been ported now by using `Span<T>` extensively...

So, maybe c++ to c# code conversion is not so far away? ... what do you think?

**Comment by StephenHodgson** [comment]
Very possible. personally I'd like to see more code generation done in this manner, but bc of the many, many different ways you can write c++ (let alone c and older versions of c++) there might still be some areas you gotta pick apart yourself or you get undefined behaviour.

**Comment by xoofx** [comment]
It's definitely not in the scope of CppAst.CodeGen, but you might have more chance in the future with a solution like [Llama](https://ericsink.com/entries/sqlite_llama_preview.html) if it gets OSS...
