### ISSUE TITLE
Unable to provide own implementation of DefaultFunctionConverter

### ISSUE THREAD

**Issue by wackoisgod** [xoofx/CppAst.CodeGen#24]
I am wanting to provide my own version of this Converter but the issue here is that `CppElement` is `internal set` on `CSharpElement` which doesn't allow me to provide the same behavior as the default nor will it allow this to work with the mapping rules later. 

Is there any specific reason this has to be internal ? Especially given the plugin architecture ?

**Comment by xoofx** [comment]
> Is there any specific reason this has to be internal ? Especially given the plugin architecture ?

I think that's probably ok to make it public. I recently fixed a behavior to setup the [link back from a CSharpType to the CppElement](https://github.com/xoofx/CppAst.CodeGen/commit/be0645946736c4ae53416342aa3cd8b2f7842a4d#diff-3d6f7f383a3ad2830e3ece9ffff14da666b27f3ba1182a1ee11de4ecf3c150e3R340)
