### ISSUE TITLE
fails to generate enum value based on macro definition

### ISSUE THREAD

**Issue by StephenHodgson** [xoofx/CppAst.CodeGen#3]
When attempting to generate an enum using a macro definition the code generated does not compile.

# Current
c++
```
/*! Macro to set a the prefix bytes of an API specific Result code. */
#define RESULT_PREFIX(val) (val << 16)

enum {
  /*! Defines the prefix for global Result codes. */
  ResultAPIPrefix_Global = RESULT_PREFIX(0),
};

enum {
  /*! Defines the prefix for AudioResult codes. */
  ResultAPIPrefix_Audio = RESULT_PREFIX(0x9e11)
};
```

C#
```CS
public enum __AnonymousCppEnum_api_3920AnonymousEnum : int
{
    /// <summary>
    /// Defines the prefix for global Result codes.
    /// </summary>
    ResultAPIPrefix_Global = unchecked((int)(0  16)enum{/*! Defines the prefix for global Result codes. */ResultAPIPrefix_Global=RESULT_PREFIX(0))),
}

public enum __AnonymousCppEnum_audio_8721AnonymousEnum : int
{
    /// <summary>
    /// Defines the prefix for AudioResult codes.
    /// </summary>
    ResultAPIPrefix_Audio = unchecked((int)(0x9e11  )), // Note this value should have also been computed using the macro.
}
```

# Expected

```CS
public enum __AnonymousCppEnum_api_3920AnonymousEnum : int
{
    /// <summary>
    /// Defines the prefix for global Result codes.
    /// </summary>
    ResultAPIPrefix_Global = unchecked((int)0 << (int)16),
}

public enum __AnonymousCppEnum_audio_8721AnonymousEnum : int
{
    /// <summary>
    /// Defines the prefix for AudioResult codes.
    /// </summary>
    ResultAPIPrefix_Audio = unchecked((int)0x9e11 << (int)16),
}
```

**Comment by xoofx** [comment]
> I'm not entirely sure what the result of this should look like, but probably a calculated value for the enum?

It should print the characters, don't know why it is not working.

PR much welcome for the various issues, as I don't have any time left dedicated for this project these days...

**Comment by StephenHodgson** [comment]
> PR much welcome for the various issues, as I don't have any time left dedicated for this project these days...

No worries, I understand. I will do my best, but I'm def not sure about this one in particular. The others I was planning on opening PRs if I solved them.

**Comment by StephenHodgson** [comment]
@xoofx this actually seems to be a problem in the [CppAst](https://github.com/xoofx/CppAst) project, as the cpp macro isn't properly applied to the `CppEnumItem.ValueExpression`.

I'm trying to track down exactly what's going on but a bit slow going.

**Comment by StephenHodgson** [comment]
@xoofx where exactly are the macros applied to the expressions?

**Comment by xoofx** [comment]
you mean [this](https://github.com/xoofx/CppAst.CodeGen/blob/e28771df6cef483bffd9cf6bec34c70880ec773b/src/CppAst.CodeGen/CSharp/Plugins/DefaultEnumItemConverter.cs#L27-L43)?

**Comment by StephenHodgson** [comment]
No, I've already fixed that in https://github.com/xoofx/CppAst.CodeGen/pull/8

**Comment by StephenHodgson** [comment]
I'm talking about more lower level in the CppAst model builder, where we're gathering all the enum expression values.

**Comment by xoofx** [comment]
https://github.com/xoofx/CppAst/blob/b27338c68fae3ab189ad58573b27a7e3547f98a9/src/CppAst/CppModelBuilder.cs#L192-L205

**Comment by StephenHodgson** [comment]
Correct. That's where I'm currently looking.

**Comment by StephenHodgson** [comment]
So after stepping through each of this I was able to figure out that the [clang tokenizer](https://github.com/xoofx/ClangSharp/blob/ed8f95a042526d79ee84ffea6c3a19813ebfbdb3/ClangSharp/Extensions/CXTranslationUnit.cs#L73) is returning back invalid tokens.

**Comment by StephenHodgson** [comment]
Seems to be fixed. Thanks!

**Comment by StephenHodgson** [comment]
Nope, I was mistaken, I must have updated my headers with the precomputed values
