### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Sojaner** [xoofx/CppAst.CodeGen#33]
I don't see any commits since couple of years ago. Is the code in a stable state or is it abandoned?

**Comment by StephenHodgson** [comment]
This library is pretty solid. Just cuz there hasn't been any commits recently doesn't mean it is dead 😅

**Comment by Sojaner** [comment]
Thanks for the quick response. 
That's nice to hear. My main concern what that it has never reached a major version.

**Comment by xoofx** [comment]
> I don't see any commits since couple of years ago. Is the code in a stable state or is it abandoned?

I haven't been using it a lot in the past months, but it still powers some of my own projects (e.g [NPlug](https://github.com/xoofx/NPlug))

The project is a bit far from where I would like it to be (e.g Ideally, it would be nice to generate new `LibraryImport` marshalling with .NET Core), so it could be improved in many ways, but I don't have a need right now. PR welcome though if you are looking for some specifics.

> That's nice to hear. My main concern what that it has never reached a major version.

Main reason is that I can break the API if it becomes necessary.

**Comment by Sojaner** [comment]
> > I don't see any commits since couple of years ago. Is the code in a stable state or is it abandoned?
> 
> I haven't been using it a lot in the past months, but it still powers some of my own projects (e.g [NPlug](https://github.com/xoofx/NPlug))
> 
> The project is a bit far from where I would like it to be (e.g Ideally, it would be nice to generate new `LibraryImport` marshalling with .NET Core), so it could be improved in many ways, but I don't have a need right now. PR welcome though if you are looking for some specifics.
> 
> > That's nice to hear. My main concern what that it has never reached a major version.
> 
> Main reason is that I can break the API if it becomes necessary.

Thanks for the elaboration. 😊👍

**Comment by xoofx** [comment]
I have started to introduce support for LibraryImport/raw delegates in commit ad07b2887883b9b9ba52c8c3fa15e35572d8b700 still a few things to test on my own project before I can publish a new package.
