### ISSUE TITLE
minor DefaultTypeConverter issue

### ISSUE THREAD

**Issue by jmkinzer** [xoofx/CppAst.CodeGen#36]
Hi,

I first wanted to say that I've probably used about every ffigen out there (and wrote my own at one point). This is far and away the most pleasant one to use and modify. So: *thank you*

I did have a quick suggestion, not worth a PR. I assume this is incorrect?
https://github.com/xoofx/CppAst.CodeGen/blob/d18a080933e1680e79215e8409b4e31445a51733/src/CppAst.CodeGen/CSharp/Plugins/DefaultTypeConverter.cs#L98

![image](https://github.com/xoofx/CppAst.CodeGen/assets/7916561/22dd0fde-09cc-4b99-8436-dceba14ef711)

**Comment by xoofx** [comment]
> I did have a quick suggestion, not worth a PR. I assume this is incorrect?

I haven't checked this one, as none of the API that I'm generating are using ref types, but what is exactly incorrect?

**Comment by xoofx** [comment]
Oh, you meant the `CppPointerType` instead of `CppReferenceType`, definitely 😅 

I'm making some changes to the lib, so will push a fix.

> I first wanted to say that I've probably used about every ffigen out there (and wrote my own at one point). This is far and away the most pleasant one to use and modify. So: thank you

Thanks! Though, be careful that this library is quite experimental, can break things, is incomplete...etc. ☺️

**Comment by jmkinzer** [comment]
Heh heh, yes, the README initially scared me off. But I was already about to roll my own one-off solution, again, using CPPAST anyway so I asked myself: "what's the worst that can happen?" :-)

I really like the plugin/pipeline structure... so far any modifications I've needed are nicely contained there.

**Comment by xoofx** [comment]
Fixed by commit 43cf812 - upcoming 0.15.0 (many fixes/small improvements in the past days)
