### ISSUE TITLE
Struct improperly generated

### ISSUE THREAD

**Issue by StephenHodgson** [xoofx/CppAst.CodeGen#5]
This one particular struct was improperly generated using a fixed keyword and a generated type.

# Result:

c++
```
/*! Desired configuration of the input system. */
typedef struct InputConfiguration {
  /*! Desired degrees-of-freedom mode of each controller. */
  InputControllerDof dof[Input_MaxControllers];
} InputConfiguration;
```

C#
```CS
/// <summary>
/// Desired configuration of the input system.
/// </summary>
[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
public unsafe partial struct InputConfiguration
{
    /// <summary>
    /// Desired degrees-of-freedom mode of each controller.
    /// </summary>
    public fixed libnative.InputControllerDof dof[2];
}
```

Error

> Fixed size buffer type must be one of the following: bool, byte, short, int, long, char, sbyte, ushort, uint, ulong, float or double

# Expected

I'm not really sure what the expected result here would be either besides replacing the generated type with the `int` equivalent value, but that doesn't seem correct.

```CS
/// <summary>
/// Desired configuration of the input system.
/// </summary>
[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
public unsafe partial struct InputConfiguration
{
    /// <summary>
    /// Desired degrees-of-freedom mode of each controller.
    /// </summary>
    public fixed int dof[2];
}
```

**Comment by xoofx** [comment]
This one is usually either handled by letting `MarshalAs` do the conversion... or do actually inline all the elements, one field per array index (but then to expose the array, it is another story as well...)
So a bit annoying to handle correctly.

**Comment by StephenHodgson** [comment]
I am curious how to use the `MarsalAs` do the conversion, but I wasn't able to figure it out on my own.
